#!/bin/bash

comm=$1
feed=$2

if [ $comm="add" ] ; then
	echo "$feed" >> /home/arturserra/.newsboat/urls
	echo "New RSS feed added successfully. Launching Newsboat"
	sleep 2
elif [ $1="show" ] ; then
	echo "Launching Newsboat"
	sleep 1
fi

newsboat -ru /home/arturserra/.newsboat/urls
