#!/bin/bash

if [ -t 0 ] ; then
	if [ -z "$1" ] ; then
		echo "Hello! This is the tny terminal url shortener"
		echo "Usage: tny original_url [custom keyword]"
		echo ""
		echo "Shorten URLs using tny.im"
		exit 1
	fi
	url=$1;
else
	while read -r line ; do
		url=$1
	done
fi

echo `wget -q -O - https://tny.im/yourls-api.php?action=shorturl\&format=simple\&url=$url\&keyword=$2`
