#!/bin/bash

data=$(date '+%A, %B %d, %Y.')
user=$(whoami)

# Add task

if [ $1 = "add" ] ; then
	echo  "$user: $2 on $data" >> /home/arturserra/Documents/todo.txt
	exit 0 
elif [ $1 = "show" ] ; then
	cat -n /home/arturserra/Documents/todo.txt
	exit 0
elif [ $1 = "del" ] ; then
	sed -i $2d /home/arturserra/Documents/todo.txt
	exit 0
fi
	
