#!/bin/bash

#Normalizes and validates month in date specification to three letters:
#Exits with 0 if no error is returned.

monthNumToName()
{
	#Sets the "Month" variable to an appropriate value

	case $1 in
		1 ) month="Jan" ;;
		2 ) month="Feb" ;;
		3 ) month="Mar" ;;
		4 ) month="Apr" ;;
		5 ) month="May" ;;
		6 ) month="Jun" ;;
		7 ) month="Jul" ;;
		8 ) month="Aug" ;;
		9 ) month="Sep" ;;
		10) month="Oct" ;;
		11) month="Nov" ;;
		12) month="Dec" ;;

		*) echo "$0: Unknown month value $1" >&2 ; exit 1
	esac

	return 0
}

#Input Validation

if [ $# -ne 3 ] ; then
	echo "Usage: $0 Month/Day/Year" >&2
	echo "Typical input formats are 'August 3 1992'" >&2 ; exit 1
fi

if [ $3 -le 99 ] ; then
	echo "$0: Expected four-digit year value." >&2 ; exit 1
fi

#Validate if the month input format is a number
if [ -z $(echo $1 | sed 's/[[:digit:]]//g') ] ; then
	monthNumToName $1
else
#Normalize to first three letters, first upper and the rest in lowercase.
	month="$(echo $1 | cut -c1 | tr '[:lower:]' '[:upper:]' )"
	month="$month$(echo $1 | cut -c2-3 | tr '[:upper:]' '[:lower:]')"
fi

echo $month $2 $3

exit 0

